name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Executa apenas quando houver push na branch main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Testar aplicação
        run: |
          python -m unittest discover tests  # Supondo que os testes estejam na pasta "tests"

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir e publicar imagem
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-api:latest

